import { Inter } from "next/font/google";
import "./globals.css";
import State from "../context/state"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <State>
      <body className={inter.className}>{children}</body>
      </State>
    </html>
  );
}
